# Generated by Django 5.0.6 on 2024-05-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencia',
            name='plato',
        ),
        migrations.DeleteModel(
            name='Plato',
        ),
    ]
