# Generated by Django 5.0.6 on 2024-05-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_comida_preferencia_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
