# Generated by Django 5.0.6 on 2024-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_alter_comida_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencia',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='preferencia',
            name='es_preferido',
        ),
        migrations.AddField(
            model_name='preferencia',
            name='nombre_plato_preferido',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='motivo_preferencia',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
    ]
