# Generated by Django 5.0.6 on 2024-05-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_remove_preferencia_comida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencia',
            name='preferido',
            field=models.BooleanField(default=False),
        ),
    ]
