# Generated by Django 5.0.6 on 2024-05-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_preferencia_preferido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='preferido',
            field=models.BooleanField(default=True),
        ),
    ]
